import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { loadTranslation } from "@/lib/i18n";
import { Navbar } from "@/components/navigations/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const allContents = await loadTranslation();
  const navbarContents = allContents["navbar"];
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" max-w-full mx-auto text-background">
          <header className="z-10 flex w-full justify-stretch">
            <Navbar lang={navbarContents.lang} navs={navbarContents.navs} />
          </header>
          <main className=" z-0">{children}</main>
          <footer></footer>
        </div>
      </body>
    </html>
  );
}
