import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navigations/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="night">
      <body className={inter.className}>
        <div className=" max-w-full mx-auto">
          <header className="z-10">
            <Navbar />
          </header>
          <main className=" z-0">{children}</main>
          <footer></footer>
        </div>
      </body>
    </html>
  );
}
